// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0hrOebxwIGiTEfYPiOJIqeQKdpIUzIT0',
    appId: '1:706774173105:web:6d9f02aacdab2150986990',
    messagingSenderId: '706774173105',
    projectId: 'planto-shopping',
    authDomain: 'planto-shopping.firebaseapp.com',
    storageBucket: 'planto-shopping.firebasestorage.app',
    measurementId: 'G-SDGNSYVVGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBs6jLnQQ3K2nkGaHabXksO7f8L1Cabk',
    appId: '1:706774173105:android:ced7a92b9a6a32dc986990',
    messagingSenderId: '706774173105',
    projectId: 'planto-shopping',
    storageBucket: 'planto-shopping.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0JHK3U2CoNSGRQMwhmmJIZqFDxAobPIc',
    appId: '1:706774173105:ios:1f220941f3b524e1986990',
    messagingSenderId: '706774173105',
    projectId: 'planto-shopping',
    storageBucket: 'planto-shopping.firebasestorage.app',
    iosBundleId: 'com.saTech.planto.plantoEcommerceApp',
  );
}
